name: Dependabot auto-merge
on: pull_request

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.ACTION_AUTOMATION_APP_ID }}
          private-key: ${{ secrets.ACTION_AUTOMATION_PRIVATE_KEY }}

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2

      - name: Enable auto-merge for Dependabot PRs
        if: contains(fromJSON('["production-minor","development","actions-minor"]'), steps.metadata.outputs.dependency-group)
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
