name: dependabot validate

on:
  pull_request:
    paths:
      - ".github/dependabot.yml"
      - ".github/workflows/dependabot-validate.yml"

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.ACTION_AUTOMATION_APP_ID }}
          private-key: ${{ secrets.ACTION_AUTOMATION_PRIVATE_KEY }}

      - uses: actions/checkout@v3
      - uses: marocchino/validate-dependabot@v2
        id: validate

      - uses: marocchino/sticky-pull-request-comment@v2
        if: always()
        with:
          header: validate-dependabot
          message: ${{ steps.validate.outputs.markdown }}
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
